name: Python Package

on:
  schedule:
    - cron: "54 16 * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/set-python@v4
        with:
          python-version: '3.9'
          
        
      - name: Install dependices
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: MakeAppointment
        run: python main.py